import type { PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function AppLayout({children}: PropsWithChildren) {  
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
